services:
  sde-workshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: sde-workshop
    container_name: sde-workshop
    ports:
      - "8888:8888"   # Jupyter Lab
      - "3001:3001"   # Jupyter Lab MCP
      - "4040-4049:4040-4049" # Spark UI
    env_file:
      - .env.spark
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/.venv

